ADMIN_EMAIL: "junglee0713@gmail.com"
PROJECT_DIR: "/scr1/users/leej39/USDA_RUN22"
BARCODES: "barcodes.txt"
CONTIGS_DB: "/scr1/users/leej39/USDA_RUN22/RUN12_blastdb"
BLASTOUT_DIR: "blast_against_contigs"
R1_FASTA_DIR: "R1_FASTA"
CONTIG_INFO_DIR: "contig_info"
SUNBEAM_OUTPUT_DIR: "sunbeam_output"
QC_DIR: "qc"
DECONTAM_DIR: "decontam"
PCTID_ALNLEN_DIR: "pctid_alnlen"
BLAST_FILTER:
    PCTID_CUT: "95"
    ALNPCT_CUT: "95"
